### ISSUE TITLE
Damage is reduced after the first few shots after leaving a bench

### ISSUE THREAD

**Issue by TheDarkestShado1** [TTacco/Hollow-Point#9]
The initial shots will have normal nail damage immediately after leaving the bench, but after the first enemy is killed, it takes 3+ hits to kill all enemies. Some enemies that were initially one shots now take two hits to kill, etc. Affects both nail and the gun.

E: It seems to be fixed after the first nail upgrade.

Using the latest version on the mod loader.

**Comment by TTacco** [comment]
I might look into this a bit further, just be an FYI gun damage has some randomness to it (I think it was like from 3-8?) so its really noticeable when you get RNG damage, so that might be it.

Already got rid of the RNG in my current build and I'm trying to implement range based damage at the moment.

**Comment by TTacco** [comment]
Turns out it was due to bullet damage RNG.

Damage is now static and it should always be consistent now.
